# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 08:01
from __future__ import unicode_literals

import cannula.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cannula', '0009_validationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/asseym/Public/VSCode/rhites_ec_web/source_doc_storage'), upload_to=cannula.models.make_random_filename),
        ),
    ]
